# Generated by Django 4.0.6 on 2022-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitting',
            name='productId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
