# Generated by Django 4.0.6 on 2022-07-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0002_fitting_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitting',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
