# Generated by Django 4.0.6 on 2022-07-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0003_alter_fitting_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitting',
            name='hit',
        ),
    ]
