# Generated by Django 4.0.6 on 2022-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0004_remove_fitting_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitting',
            name='upd_date',
            field=models.DateField(auto_now=True),
        ),
    ]
